import { mentionGate } from './mention.js';

const DEV_ASSIST_MARKERS = [
  /## Dev-Assist:/i,
  /generated by Dev-Assist/i,
  /Full context file generated by Dev-Assist/i,
  /Dev-Assist Context/i,
];

export function isDevAssistGeneratedNote(note: any): boolean {
  const body = String(note?.body || note?.note || '').trim();
  if (!body) return false;

  return DEV_ASSIST_MARKERS.some((re) => re.test(body));
}

export function isDeletableNote(note: any): boolean {
  if (!note || note.system) return false;
  const body = String(note.body || note.note || '').trim();
  if (!body) return false;

  if (mentionGate.hasMention(body)) return true;

  return isDevAssistGeneratedNote(note);
}

export function filterDeletableNotes(notes: any[]): any[] {
  if (!Array.isArray(notes)) return [];
  return notes.filter(isDeletableNote);
}
