import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { isDeletableNote, filterDeletableNotes } from '../src/services/gitlab/cleanup';

describe('GitLab Comment Cleanup Filter', () => {
  it('does not delete system notes', () => {
    const note = {
      system: true,
      body: '@dev-assist publish',
    };
    assert.equal(isDeletableNote(note), false);
  });

  it('does not delete empty comments', () => {
    const note = {
      system: false,
      body: '',
    };
    assert.equal(isDeletableNote(note), false);
  });

  it('deletes comments mentioning @dev-assist', () => {
    const note1 = { system: false, body: '@dev-assist process' };
    const note2 = { system: false, body: '**@dev-assist** publish' };
    const note3 = { system: false, body: '   @dev-assist' };

    assert.equal(isDeletableNote(note1), true);
    assert.equal(isDeletableNote(note2), true);
    assert.equal(isDeletableNote(note3), true);
  });

  it('deletes comments containing Dev-Assist generated markers', () => {
    const note1 = { system: false, body: '## Dev-Assist:\nSome context here.' };
    const note2 = { system: false, body: 'This context was generated by Dev-Assist' };
    const note3 = { system: false, body: '# Dev-Assist Context\nSome more details' };

    assert.equal(isDeletableNote(note1), true);
    assert.equal(isDeletableNote(note2), true);
    assert.equal(isDeletableNote(note3), true);
  });

  it('keeps normal user comments that do not contain markers or mentions', () => {
    const note = {
      system: false,
      body: 'Can we also add Google Login support to this task?',
    };
    assert.equal(isDeletableNote(note), false);
  });

  it('filters a list of notes returning only deletable ones', () => {
    const notes = [
      { id: 1, system: false, body: 'Keep me!' },
      { id: 2, system: false, body: '@dev-assist publish' },
      { id: 3, system: true, body: 'System note generated by @dev-assist' },
      { id: 4, system: false, body: '## Dev-Assist:\nProposal details...' },
    ];

    const result = filterDeletableNotes(notes);
    assert.equal(result.length, 2);
    assert.equal(result[0].id, 2);
    assert.equal(result[1].id, 4);
  });
});
