import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { renderClarificationComment, renderRequirementAnalysis } from '../src/services/ai/formatter';
import { RequirementAnalysis } from '../src/services/ai/schema';

describe('Markdown Formatter Service', () => {
  const baseAnalysis: RequirementAnalysis = {
    title: 'Implementation Title',
    description: ['First description paragraph.', 'Second description paragraph.'],
    acceptanceCriteria: ['criteria 1', 'criteria 2'],
    technicalContext: ['note 1'],
    proposedSolution: ['task 1', 'task 2'],
    openQuestions: [],
  };

  it('renders the approved compact ticket structure', () => {
    const doc = renderRequirementAnalysis(baseAnalysis);
    assert.equal(doc, [
      '## 📋 Description',
      '',
      'First description paragraph.',
      '',
      'Second description paragraph.',
      '',
      '## 🎯 Acceptance Criteria',
      '',
      '- criteria 1',
      '- criteria 2',
      '',
      '## 📁 Technical Context & Logs',
      '',
      '- note 1',
      '',
      '## 💡 Proposed Solution',
      '',
      '1. task 1',
      '2. task 2',
    ].join('\n'));
    assert.doesNotMatch(doc, /Implementation Title/);
    assert.doesNotMatch(doc, /Dev-Assist Context|Generated by Dev-Assist/);
  });

  it('uses fallback text for empty visible sections', () => {
    const doc = renderRequirementAnalysis({
      ...baseAnalysis,
      description: [],
      acceptanceCriteria: [],
      technicalContext: [],
      proposedSolution: [],
    });
    assert.equal(doc.match(/Not enough information available yet\./g)?.length, 4);
  });

  it('normalizes items and keeps a remaining question in technical context', () => {
    const doc = renderRequirementAnalysis({
      ...baseAnalysis,
      description: ['  paragraph with\nline break  ', ''],
      proposedSolution: ['1. inspect header', '2) add toggle'],
      openQuestions: ['Should system changes be followed after initial load?'],
    });
    assert.match(doc, /paragraph with line break/);
    assert.match(doc, /- Open question: Should system changes be followed after initial load\?/);
    assert.match(doc, /1\. inspect header/);
    assert.match(doc, /2\. add toggle/);
    assert.doesNotMatch(doc, /1\. 1\.|2\. 2\)/);
  });

  it('neutralizes leading Markdown block syntax without changing the four-section structure', () => {
    const doc = renderRequirementAnalysis({
      ...baseAnalysis,
      description: [
        '## Extra section\rheading body',
        '```ts\r\nsource text\n```',
        '> quoted description',
        '- bullet-like description',
        '7. numbered-like description',
      ],
      acceptanceCriteria: ['> quoted criterion'],
      technicalContext: ['- bullet-like context'],
      proposedSolution: ['1. numbered solution', '```sh\rcommand\r```'],
    });

    assert.deepEqual(doc.match(/^## .+$/gm), [
      '## 📋 Description',
      '## 🎯 Acceptance Criteria',
      '## 📁 Technical Context & Logs',
      '## 💡 Proposed Solution',
    ]);
    assert.doesNotMatch(doc, /^(?:```|~~~)/m);
    assert.doesNotMatch(doc, /\r/);
    assert.match(doc, /Extra section heading body/);
    assert.match(doc, /```ts source text ```/);
    assert.match(doc, /quoted description/);
    assert.match(doc, /bullet-like description/);
    assert.match(doc, /numbered-like description/);
    assert.match(doc, /quoted criterion/);
    assert.match(doc, /bullet-like context/);
    assert.match(doc, /1\. numbered solution/);
    assert.match(doc, /```sh command ```/);
  });

  it('neutralizes unspaced and spaced thematic breaks in every visible item style', () => {
    const thematicBreaks = ['---', '- - -', '***', '* * *', '___', '_ _ _'];
    const doc = renderRequirementAnalysis({
      ...baseAnalysis,
      description: thematicBreaks,
      acceptanceCriteria: thematicBreaks,
      technicalContext: thematicBreaks,
      proposedSolution: thematicBreaks.map((item, index) => index === 0 ? `1. ${item}` : item),
    });
    const lines = doc.split('\n');

    assert.deepEqual(doc.match(/^## .+$/gm), [
      '## 📋 Description',
      '## 🎯 Acceptance Criteria',
      '## 📁 Technical Context & Logs',
      '## 💡 Proposed Solution',
    ]);
    for (const [index, item] of thematicBreaks.entries()) {
      const escapedItem = `\\${item}`;
      assert.ok(lines.includes(escapedItem), `description must display ${item} literally`);
      assert.equal(
        lines.filter((line) => line === `- ${escapedItem}`).length,
        2,
        `acceptance criteria and technical context must display ${item} as bullets`,
      );
      assert.ok(
        lines.includes(`${index + 1}. ${escapedItem}`),
        `proposed solution must display ${item} as an automatically numbered item`,
      );
      assert.ok(!lines.includes(item), `description must not emit raw thematic break ${item}`);
      assert.ok(!lines.includes(`- ${item}`), `bullet sections must not emit raw thematic break ${item}`);
      assert.ok(
        !lines.includes(`${index + 1}. ${item}`),
        `proposed solution must not emit raw thematic break ${item}`,
      );
    }
    assert.doesNotMatch(doc, /^1\. 1\./m);
  });

  it('renders clarification comments with open questions', () => {
    const comment = renderClarificationComment({
      ...baseAnalysis,
      openQuestions: ['question 1', 'question 2'],
    });
    assert.match(comment, /## Dev-Assist: More information needed/);
    assert.match(comment, /- question 1/);
    assert.match(comment, /- question 2/);
    assert.match(comment, /Current best guess for title: Implementation Title/);
  });

  it('renders clarification comments with fallback text when questions are missing', () => {
    const comment = renderClarificationComment(baseAnalysis);
    assert.match(comment, /There are several unclear areas regarding the requirements/);
  });
});
