import type { OpencodeClient } from "@opencode-ai/sdk";
import logger from "./logger.js";
import { joinTextParts } from "./opencode-parts.js";
import type { OpencodeResponsePart } from "./types.js";

/**
 * Repository summary provider.
 *
 * A single repository summary (technology stack, project structure, key
 * commands, architecture, important files, conventions) is generated by the
 * Opencode agent for the working repository and cached in memory so it can be
 * attached to every dev-assist request. It is (re)generated on server start and
 * after every merge request.
 */

let cachedSummary: string | null = null;
let lastGeneratedAt: number | null = null;
let inFlight: Promise<string | null> | null = null;

const SUMMARY_PROMPT = `Analyze the current repository and produce the repository summary now, following your instructions and section structure exactly. Return only the Markdown summary.`;

/**
 * Returns the most recently generated repository summary, or null if none has
 * been generated yet.
 */
export function getRepositorySummary(): string | null {
  return cachedSummary;
}

/**
 * Timestamp (ms since epoch) of the last successful generation, or null.
 */
export function getRepositorySummaryTimestamp(): number | null {
  return lastGeneratedAt;
}

/**
 * Overwrites the cached summary. Passing null clears it.
 */
export function setRepositorySummary(summary: string | null): void {
  cachedSummary = summary && summary.trim() ? summary.trim() : null;
  lastGeneratedAt = cachedSummary ? Date.now() : null;
}

/**
 * Formats the cached summary for inclusion in an agent prompt.
 */
export function formatRepositorySummaryForPrompt(): string {
  return cachedSummary ?? "(No repository summary is available yet.)";
}

/**
 * Runs the Opencode `repo-summary` agent to generate a fresh summary of the
 * working repository. Throws on failure; callers that want to keep the previous
 * summary should use {@link refreshRepositorySummary}.
 */
export async function generateRepositorySummary(opencodeClient: OpencodeClient): Promise<string> {
  logger.info("[REPO-SUMMARY] Generating repository summary...");

  const sessionRes = await opencodeClient.session.create();
  if (!sessionRes.data || !sessionRes.data.id) {
    throw new Error("Failed to create Opencode session for repository summary: no session ID returned");
  }
  const sessionId = sessionRes.data.id;

  try {
    const promptRes = await opencodeClient.session.prompt({
      path: { id: sessionId },
      body: {
        agent: "repo-summary",
        parts: [{ type: "text", text: SUMMARY_PROMPT }]
      }
    });

    if (!promptRes.data || !promptRes.data.parts) {
      throw new Error("Failed to get repository summary from Opencode session: no parts returned.");
    }

    const summary = joinTextParts(promptRes.data.parts as OpencodeResponsePart[]).trim();
    if (!summary) {
      throw new Error("Opencode returned an empty repository summary.");
    }

    logger.info(`[REPO-SUMMARY] Generated repository summary (${summary.length} chars).`);
    return summary;
  } finally {
    await opencodeClient.session.delete({ path: { id: sessionId } }).catch(err => {
      logger.error(`[REPO-SUMMARY] Failed to delete session ${sessionId}: ` + err.message);
    });
  }
}

/**
 * Generates a fresh summary and updates the cache. On failure the previous
 * summary is kept and returned. Concurrent calls share a single in-flight
 * generation so a burst of merge requests doesn't spawn redundant sessions.
 */
export async function refreshRepositorySummary(opencodeClient: OpencodeClient): Promise<string | null> {
  if (inFlight) {
    logger.debug("[REPO-SUMMARY] Refresh already in progress; awaiting existing generation.");
    return inFlight;
  }

  inFlight = (async () => {
    try {
      const summary = await generateRepositorySummary(opencodeClient);
      setRepositorySummary(summary);
      return cachedSummary;
    } catch (err) {
      logger.error("[REPO-SUMMARY] Failed to refresh repository summary: " + (err as Error).message);
      return cachedSummary; // keep whatever we had before
    } finally {
      inFlight = null;
    }
  })();

  return inFlight;
}
